name: "Build and cache NixOS configurations"
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cache.yaml"
      - ".tack/pins.lock.json"
      - "hosts/**/facter.json"
      - "**/*.nix"
      - "**/*.lua"
jobs:
  build-nix-configurations:
    name: "Build NixOS configurations and push to Cachix"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: '${{ secrets.GH_ACCESS_TOKEN }}'

    - name: Configure Cachix
      uses: cachix/cachix-action@v17
      with:
        name: misterkartoffel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check flake
      run: nix flake check

    - name: Enter default devShell
      run: nix develop .#default

    - name: Build NixOS configurations
      run: |
        set -euo pipefail

        while read -r host; do
          echo "::group::Building $host"
          nix build ".#nixosConfigurations.$host.config.system.build.toplevel"
          echo "::endgroup::"
        done < <(nix eval --json ".#nixosConfigurations" --apply builtins.attrNames | jq -r ".[]")
