---
name: "Build flake outputs"

on:
  push:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  treefmt:
    name: "Check formatting"
    runs-on: ubuntu-latest

    steps:
    - name: "Set up Nix"
      uses: $/.github/actions/nix

    - name: "Run formatter"
      run: nix fmt -- --ci

  check:
    name: "Check flake"
    runs-on: ubuntu-latest

    steps:
    - name: "Set up Nix"
      uses: $/.github/actions/nix
      with:
        github-token: ${{ secrets.GH_PAT_SECRETS_RO }}

    - name: "Run flake check"
      run: nix flake check --all-systems

  matrix:
    name: "Create builder matrix"
    runs-on: ubuntu-latest

    steps:
    - name: "Set up Nix"
      uses: $/.github/actions/nix
      with:
        github-token: ${{ secrets.GH_PAT_SECRETS_RO }}

    - name: "Set up hestia"
      uses: Mic92/hestia@v3.0.1

    - name: "Discover matrix"
      id: matrix
      uses: Mic92/hestia/matrix@v3.0.1
      with:
        flake: ".#hydraJobs"
        nix-eval-jobs: "nix run nixpkgs#nix-eval-jobs -- --force-recurse"

    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      any-jobs: ${{ steps.matrix.outputs.any-jobs }}
      manifest-version: ${{ steps.matrix.outputs.manifest-version }}

  build:
    name: "${{ matrix.name }} (${{ matrix.system }})"
    needs: matrix
    if: needs.matrix.outputs.any-jobs == 'true'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}

    steps:
    - name: "Install Nix"
      uses: cachix/install-nix-action@v31.11.1
      with:
        github_access_token: ${{ secrets.GH_PAT_SECRETS_RO }}
        extra_nix_config: |
          keep-going = true
          cores = 0

    - name: "Setup Cachix"
      uses: cachix/cachix-action@v17
      continue-on-error: true
      with:
        name: misterkartoffel
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: "Set up hestia"
      uses: Mic92/hestia@v3.0.1
      with:
        wait-manifest-version: ${{ needs.matrix.outputs.manifest-version }}

    - name: "Prefetch drv closure"
      run: ${HESTIA_BIN} prefetch ${{ matrix.installables }}

    - name: "Build ${{ matrix.name }}"
      run: >-
        nix build
        ${{ matrix.installables }}
        --print-build-logs
