name: "Build flake outputs"

on:
  push:
    paths:
      - ".github/workflows/build.yaml"
      - ".tack/pins.lock.json"
      - "hosts/**/facter.json"
      - "**/*.nix"
      - "**/*.lua"
  pull_request:
    paths:
      - ".github/workflows/build.yaml"
      - ".tack/pins.lock.json"
      - "hosts/**/facter.json"
      - "**/*.nix"
      - "**/*.lua"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  treefmt:
    name: "Check formatting"
    runs-on: ubuntu-latest

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              extra_nix_config: |
                keep-going = true
                cores = 0

      - name: "Run formatter"
        run: nix fmt -- --ci

  check:
    name: "Check flake"
    runs-on: ubuntu-latest

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              extra_nix_config: |
                keep-going = true
                cores = 0

      - name: "Check flake"
        run: nix flake check --all-systems

  matrix:
    name: "Create builder matrix"
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              extra_nix_config: |
                keep-going = true
                cores = 0

      - name: "Discover matrices"
        id: matrix
        run: |
          for OUTPUT in shells packages hosts; do
            echo "::group::Evaluating ${OUTPUT}"
            echo "${OUTPUT}=$(nix eval --json --file ./ci/matrix.nix --apply "x: x.$OUTPUT")" >> "${GITHUB_OUTPUT}"
            echo "::endgroup::"
          done

    outputs:
      shells: ${{ steps.matrix.outputs.shells }}
      packages: ${{ steps.matrix.outputs.packages }}
      hosts: ${{ steps.matrix.outputs.hosts }}

  shells:
    name: "Build devShell: ${{ matrix.shell }} (${{ matrix.system }})"
    runs-on: ${{ matrix.runner }}
    needs:
      - matrix
      - check

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.shells) }}

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              extra_nix_config: |
                keep-going = true
                cores = 0

      - uses: cachix/cachix-action@v17
        continue-on-error: true
        with:
          name: misterkartoffel
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: "Build devShell"
        run: nix build ".#devShells.${{ matrix.system }}.${{ matrix.shell }}" --print-build-logs

  packages:
    name: "Build package: ${{ matrix.package }} (${{ matrix.system }})"
    runs-on: ${{ matrix.runner }}
    needs:
      - matrix
      - check

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.packages) }}

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              extra_nix_config: |
                keep-going = true
                cores = 0

      - uses: cachix/cachix-action@v17
        continue-on-error: true
        with:
          name: misterkartoffel
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: "Build package"
        run: nix build ".#packages.${{ matrix.system }}.${{ matrix.package }}" --print-build-logs

  hosts:
    name: "Build host: ${{ matrix.hostname }} (${{ matrix.system }})"
    runs-on: ${{ matrix.runner }}
    needs:
      - matrix
      - check

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.hosts) }}

    steps:
      - parallel:
          - uses: actions/checkout@v7.0.1
          - uses: cachix/install-nix-action@v31.11.1
            with:
              github_access_token: ${{ secrets.GH_PAT_SECRETS_RO }}
              extra_nix_config: |
                keep-going = true
                cores = 0

      - uses: cachix/cachix-action@v17
        continue-on-error: true
        with:
          name: misterkartoffel
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: "Build configuration"
        run: nix build ".#${{ matrix.platform }}Configurations.${{ matrix.hostname }}.config.system.build.toplevel" --print-build-logs
