---
name: "Flake CI"
run-name: "${{ github.workflow }}: ${{ github.event.pull_request.title || github.ref }} (#${{ github.run_number }}-${{ github.run_attempt }})"

on:
  pull_request:
    paths-ignore:
    - ".github/workflows/**"
    - "ci/**"
  push:
    branches:
    - main
    paths-ignore:
    - ".github/workflows/**"
    - "ci/**"
  workflow_dispatch:
  workflow_call:
    inputs:
      jobs:
        description: "JSON list of jobs to run"
        required: true
        type: string
      caller_event:
        description: "Event that triggered the parent workflow"
        required: true
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  treefmt:
    uses: $/.github/workflows/treefmt.yml
    if: >
      github.event_name != 'workflow_call' ||
      contains(fromJSON(inputs.jobs), 'treefmt')
    permissions:
      actions: read
    secrets: inherit

  check:
    uses: $/.github/workflows/check.yml
    if: >
      github.event_name != 'workflow_call' ||
      contains(fromJSON(inputs.jobs), 'check')
    permissions:
      actions: read
    secrets: inherit

  matrix:
    uses: $/.github/workflows/matrix.yml
    if: >
      github.event_name != 'workflow_call' ||
      contains(fromJSON(inputs.jobs), 'matrix')
    permissions:
      pull-requests: read

  shells:
    uses: $/.github/workflows/build.yml
    if: >
      github.event_name != 'workflow_call' ||
      contains(fromJSON(inputs.jobs), 'build')
    needs:
    - matrix
    - check
    with:
      target: "shell"
      matrix: ${{ needs.matrix.outputs.shells }}
    permissions:
      actions: read
    secrets: inherit

  packages:
    uses: $/.github/workflows/build.yml
    if: >
      github.event_name != 'workflow_call' ||
      contains(fromJSON(inputs.jobs), 'build')
    needs:
    - matrix
    - check
    with:
      target: "package"
      matrix: ${{ needs.matrix.outputs.packages }}
    permissions:
      actions: read
    secrets: inherit

  hosts:
    uses: $/.github/workflows/build.yml
    if: |
      github.event_name != 'pull_request' && (
        inputs.caller_event != 'pull_request' &&
        contains(fromJSON(inputs.jobs), 'build')
      )
    needs:
    - matrix
    - check
    with:
      target: "host"
      matrix: ${{ needs.matrix.outputs.hosts }}
    permissions:
      actions: read
    secrets: inherit
