---
name: "Matrix Build"

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  eval:
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.eval.outputs.jobs }}
    steps:
    - uses: actions/checkout@v7.0.1
    - uses: cachix/install-nix-action@v31.11.1
    - uses: Mic92/hestia@8630d70f9f9a3fbdf889d0f42133bd458fdd3465
    - id: eval
      run: |
        nix run nixpkgs#nix-eval-jobs -- --flake .#hydraJobs > jobs.json
        jq -r '.drvPath' jobs.json | xargs "${HESTIA_BIN}" hook --socket "${HESTIA_SOCKET}"
        echo "jobs=$(jq -sc . jobs.json)" >> "${GITHUB_OUTPUT}"

  build:
    needs: eval
    name: "${{ matrix.job.name }} (${{ matrix.job.system }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.eval.outputs.jobs) }}
    steps:
    - uses: cachix/install-nix-action@v31.11.1
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux aarch64-darwin
          keep-going = true
          cores = 0
    - uses: Mic92/hestia@8630d70f9f9a3fbdf889d0f42133bd458fdd3465
    - run: nix build "${{ matrix.job.drvPath }}^*"
