---
name: "Matrix"

on:
  workflow_call:
    outputs:
      shells:
        value: ${{ jobs.matrix.outputs.shells }}
      packages:
        value: ${{ jobs.matrix.outputs.packages }}
      hosts:
        value: ${{ jobs.matrix.outputs.hosts }}

jobs:
  matrix:
    name: "Generate builder matrix"
    runs-on: ubuntu-latest

    steps:
    - parallel:
      - name: "Checkout repository"
        uses: actions/checkout@v7.0.1

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          github_access_token: ${{ secrets.GH_PAT_SECRETS_RO }}
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Set up Hestia"
      uses: Mic92/hestia@v3.0.1

    - name: "Discover matrices"
      id: matrix
      run: |
        for OUTPUT in shells packages hosts; do
          echo "::group::Evaluating ${OUTPUT}"
          VALUE="$(nix eval --json --file ./ci/matrix.nix --apply "x: x.${OUTPUT}")"
          jq -r '.[].drvPath' <<< "${VALUE}" | xargs "${HESTIA_BIN}" hook --socket "${HESTIA_SOCKET}"
          echo "${OUTPUT}=${VALUE}" >> "${GITHUB_OUTPUT}"
          echo "::endgroup::"
        done

    outputs:
      shells: ${{ steps.matrix.outputs.shells }}
      packages: ${{ steps.matrix.outputs.packages }}
      hosts: ${{ steps.matrix.outputs.hosts }}
