---
name: "Mock CI"

on:
  workflow_call:
    inputs:
      jobs:
        description: "List of jobs to validate"
        required: true
        type: string

jobs:
  formatter:
    if: ${{ contains(fromJSON(inputs.jobs), 'formatter') }}
    uses: $/.github/workflows/formatter.yml
    with:
      validate: true

  check:
    if: ${{ contains(fromJSON(inputs.jobs), 'check') }}
    uses: $/.github/workflows/check.yml
    with:
      validate: true

  matrix:
    if: ${{ contains(fromJSON(inputs.jobs), 'matrix') }}
    uses: $/.github/workflows/matrix.yml

  shells:
    if: ${{ contains(fromJSON(inputs.jobs), 'build') }}
    uses: $/.github/workflows/build.yml
