name: Update tack pins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: tack-update
  cancel-in-progress: false

jobs:
  update:
    name: Update tack pins
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github_pat: ${{ secrets.GH_PAT_SECRETS_RO }}
          use_cachix: true

      - name: Get update summary
        id: summary
        run: |
          summary="$(nix develop .#tack --command tack look --verbose)"

          {
            echo "summary<<EOF"
            echo "${summary}"
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

      - name: Run tack update
        run: nix develop .#tack --command tack update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_PAT_CONFIG_PR }}
          branch: tack/update-inputs
          delete-branch: true
          commit-message: "tack: update inputs"
          title: "tack: update inputs"
          body: |
            ## tack update summary:

            <details>
            <summary>Click to view <code>tack look --verbose</code> output</summary>

            ```text
            ${{ steps.summary.outputs.summary }}
            ```

            </details>
