---
name: "Update Inputs"
run-name: "${{ github.workflow }} (#${{ github.run_number }}-${{ github.run_attempt }})"

on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

concurrency:
  group: tack-update
  cancel-in-progress: false

jobs:
  update:
    name: "Update tack pins"
    runs-on: ubuntu-latest
    env:
      TACK_NIX_CONF_TOKENS: 1

    outputs:
      summary: ${{ steps.summary.outputs.summary }}

    steps:
    - parallel:
      - name: "Checkout tack directory"
        uses: actions/checkout@v7.0.1
        with:
          sparse-checkout: |
            .tack

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          github_access_token: ${{ secrets.GH_PAT_SECRETS_RO }}
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Get update summary"
      id: summary
      run: |
        SUMMARY="$(nix run nixpkgs#tack -- look --verbose)"

        {
          echo "SUMMARY<<EOF"
          echo "${SUMMARY}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: "Run tack update"
      run: nix run nixpkgs#tack -- update

    - name: "Upload changes"
      uses: actions/upload-artifact@v7
      with:
        name: tack
        path: .tack
        include-hidden-files: true

  matrix:
    uses: $/.github/workflows/matrix.yml
    needs: update
    with:
      eval: "[\"hosts\"]"
    permissions:
      actions: read
      pull-requests: read
    secrets: inherit

  diffs:
    name: "Generate diffs"
    needs: matrix
    runs-on: ${{ matrix.runner }}

    permissions:
      actions: read

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.hosts) }}

    steps:
    - parallel:
      - name: "Checkout repository"
        uses: actions/checkout@v7.0.1

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          github_access_token: ${{ secrets.GH_PAT_SECRETS_RO }}
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Set up Hestia"
      uses: Mic92/hestia@v3.0.1
      with:
        upstream-cache-filter: true
        upstream-cache-key-names: >
          cache.nixos.org-1
          misterkartoffel.cachix.org-1

    - name: "Set up Cachix"
      uses: cachix/cachix-action@v17
      continue-on-error: true
      with:
        name: misterkartoffel

    - name: "Build old closure"
      id: old
      run: >
        CLOSURE="$(nix build
        "${{ matrix.drvPath }}^*"
        --no-link
        --print-out-paths)"

        echo "closure=${CLOSURE}" >> "${GITHUB_OUTPUT}"

    - name: "Download changes"
      uses: actions/download-artifact@v8.0.1
      with:
        name: tack
        path: .tack

    - name: "Build new closure"
      id: new
      run: >
        CLOSURE="$(nix build
        ".#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel"
        --no-link
        --print-out-paths)"

        echo "closure=${CLOSURE}" >> "${GITHUB_OUTPUT}"

    - name: "Generate diff"
      id: diff
      run: |
        nix run nixpkgs#dix -- --output json \
          "${{ steps.old.outputs.closure }}" \
          "${{ steps.new.outputs.closure }}" \
          > ./ci/diff.json

        nix eval --raw --file ./ci/diff.nix \
          > "${{ matrix.hostname }}.svg"

    - name: "Upload diff failure"
      if: steps.diff.outcome == 'failure'
      uses: actions/upload-artifact@v7
      with:
        name: failure-${{ matrix.hostname }}
        path: ci/diff.json

    - name: "Upload diff"
      uses: actions/upload-artifact@v7
      with:
        name: diff-${{ matrix.hostname }}
        path: ${{ matrix.hostname }}.svg

  pull-request:
    name: "Create pull request"
    needs:
    - update
    - diffs
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1

    - name: "Download changes"
      uses: actions/download-artifact@v8.0.1
      with:
        name: tack
        path: .tack

    - name: "Download diffs"
      uses: actions/download-artifact@v8.0.1
      with:
        pattern: diff-*
        path: ci/diffs
        merge-multiple: true

    - name: "Create pull request body"
      id: body
      run: |
        {
          echo "TEXT<<EOF"
          echo "## tack update summary:"
          echo
          echo '```text'
          echo "${{ needs.update.outputs.summary }}"
          echo '```'
          echo
          echo "## Closure diffs"

          for FILE in ci/diffs/*.svg; do
            HOSTNAME="${FILE##*/}"
            HOSTNAME="${HOSTNAME%.svg}"

            echo "### ${HOSTNAME}"
            echo
            echo "![${HOSTNAME} closure diff](${FILE})"
            echo
          done

          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: "Create pull request"
      id: pull-request
      uses: peter-evans/create-pull-request@v8
      with:
        branch: tack/update-inputs
        delete-branch: true
        commit-message: "tack: update inputs"
        sign-commits: true
        assignees: ${{ github.repository_owner }}
        reviewers: ${{ github.repository_owner }}
        title: "tack: update inputs"
        body: ${{ steps.body.outputs.text }}

    - name: "Attach diff images"
      if: steps.pull-request.outputs.pull-request-number != ''
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ATTACHMENTS=()

        for FILE in ci/diffs/*.svg; do
          ATTACHMENTS+=(--attach "$FILE")
        done

        gh pr edit \
          "${{ steps.pull-request.outputs.pull-request-number }}" \
          "${ATTACHMENTS[@]}"
