---
name: "Validate Workflows"
run-name: "${{ github.workflow }}: ${{ github.event.pull_request.title || github.ref }} (#${{ github.run_number }}-${{ github.run_attempt }})"

on:
  push:
    paths:
    - ".github/workflows/**"
    - "ci/**"
  pull_request:
    paths:
    - ".github/workflows/**"
    - "ci/**"

concurrency:
  group: "validate-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  lint:
    name: "Lint workflows"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1
      with:
        sparse-checkout: |
          .github
          .tack
          ci

    - parallel:
      - name: "Actionlint"
        uses: kjanat/actionlint@v1.15.1

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Run formatter on CI"
      run: nix fmt -- --ci ./ci

  filter:
    name: "Filter modified jobs"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1
      with:
        sparse-checkout: |
          .github/workflows

    - name: "Create filter"
      uses: dorny/paths-filter@v4.0.3
      id: filter
      with:
        filters: |
          flake: &flake
            - ".github/workflows/flake.yml"
          matrix: &matrix
            - *flake
            - ".github/workflows/matrix.yml"
          build: &build
            - *matrix
            - ".github/workflows/build.yml"
          check: &check
            - *build
            - ".github/workflows/check.yml"
          formatter: &formatter
            - *flake
            - ".github/workflows/formatter.yml"
          ci:
            - *flake
            - *matrix
            - *build
            - *check
            - *formatter

          gc:
            - ".github/workflows/gc.yml"

          tack:
            - ".github/workflows/tack.yml"

    outputs:
      changes: ${{ steps.filter.outputs.changes }}

  flake:
    name: "Flake CI"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'ci')
    uses: $/.github/workflows/flake.yml
    with:
      jobs: ${{ needs.filter.outputs.changes }}
    permissions:
      actions: read
      pull-requests: read
    secrets: inherit

  tack:
    name: "Updater CI"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'tack')
    uses: $/.github/workflows/tack.yml
    with:
      called: true
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit

  cache:
    name: "Cache CI"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'gc')
    uses: $/.github/workflows/gc.yml
    with:
      dry-run: true
    permissions:
      actions: write
      contents: read
    secrets: inherit
