---
name: "Validate Workflows"
run-name: "${{ github.workflow }}: ${{ github.ref_name }} (#${{ github.run_number }}-${{ github.run_attempt }})"

on:
  push:
    paths:
    - ".github/workflows/**"
    - "ci/**"
  pull_request:
    paths:
    - ".github/workflows/**"
    - "ci/**"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  lint:
    name: "Lint workflows"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1
      with:
        sparse-checkout: |
          .github
          .tack
          ci

    - parallel:
      - name: "Actionlint"
        uses: kjanat/actionlint@v1.15.1

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Run formatter on CI"
      run: nix fmt -- --ci ./ci
