---
name: "Validate Workflows"
run-name: "${{ github.workflow }}: ${{ github.event.pull_request.title || github.ref }} (#${{ github.run_number }}-${{ github.run_attempt }})"

on:
  push:
    paths:
    - ".github/workflows/**"
    - "ci/**"
  pull_request:
    paths:
    - ".github/workflows/**"
    - "ci/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  lint:
    name: "Lint workflows"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1
      with:
        sparse-checkout: |
          .github
          .tack
          ci

    - parallel:
      - name: "Actionlint"
        uses: kjanat/actionlint@v1.15.1

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.11.1
        with:
          extra_nix_config: |
            keep-going = true
            cores = 0

    - name: "Run formatter on CI"
      run: nix fmt -- --ci ./ci

  filter:
    name: "Filter modified jobs"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7.0.1
      with:
        sparse-checkout: .github/workflows

    - name: "Create filter"
      uses: dorny/paths-filter@v4.0.3
      id: filter
      with:
        list-files: json
        filters: |
          flake: &flake
            - ".github/workflows/flake.yaml"
          matrix: &matrix
            - *flake
            - ".github/workflows/matrix.yaml"
          build: &build
            - *matrix
            - ".github/workflows/build.yaml"
          check: &check
            - *build
            - ".github/workflows/check.yaml"
          treefmt: &treefmt
            - *flake
            - ".github/workflows/treefmt.yaml"
          ci:
            - *flake
            - *matrix
            - *build
            - *check
            - *treefmt

          gc:
            - ".github/workflows/gc.yaml"

          tack:
            - ".github/workflows/tack.yaml"

    outputs:
      changes: ${{ steps.filter.outputs.changes }}

  flake:
    name: "Validate CI"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'ci')
    uses: $/.github/workflows/flake.yaml
    with:
      jobs: ${{ needs.filter.outputs.changes }}
    permissions:
      actions: read
      pull-requests: read

  tack:
    name: "Validate updater"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'tack')
    uses: $/.github/workflows/tack.yaml
    permissions:
      contents: write
      pull-requests: write

  gc:
    name: "Validate GC"
    needs: filter
    if: contains(fromJSON(needs.filter.outputs.changes), 'gc')
    uses: $/.github/workflows/gc.yaml
    with:
      dry-run: true
    permissions:
      actions: write
      contents: read
